language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -p ci
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: 2eRkB9TcNhXJI1jQTWekHJqIp4LVRqf+cAU1ESWEC+cXoHaRn0dzqGDc3e3YqCvLW0Bx1hJQefUFGVOosNokTuJFpsCh/trzy0vHP7z4kU6b9G7OOS1HUx9Y0G4gEA+Mgvs/PlIlS7pSfPRJz9Oqc07wr3+PzgMtGqBd0LioB1iegq5O9rqVy5uEL0kJ4F85i9BnW29yaFQkmAItRiN7t9m5Y2x/NFp6D7IMIR/wpnPxcEa1S7jwb4LWEBY6sxtG1XH7QsnVaMc134aZv/e4AlXJq1sn0QRTZyWpgNYLQbdTfsz0b3Ki+JligUQGY9OcuWrDKxK6yYW/FBoV6XTsJSuWeP2xKrQ/E18JCd3gNqqC783fVc6dNX7gBF/47A1EhxA+fw0qTLMpINyPmvhGN+MfaLqtt/O9LgOALotwTYea4FwIaEDOFNrBv5QzxvfGOGd3gga8Hkohw7twkqraAs4rfkKSr8akKhKcapX4hqQQiLUhaUmpK80U4P8CW6ZlVQkrSigmDz/JxDTtuN01ycHfFoXIFkEFv2Y+puah282i5uh8iGvkZvuFk1hNswoE1l4xxDySXEbUTnyKi2iBkoqWpubYc7T8HRk+zTToj/Pq31coZ02BZwDfmMsnNfeg5MvFcX3W+Rswg6KbNuS9A1nhoUbabAi7VMb1yOuEdOw=
